### PR TITLE
Add event data to agencies json response

### PR DESCRIPTION
**Pull request by nvengal**
This PR adds the ability to search for agencies by the date of an event. It also adds event_date information into the agency serializer so that event dates are returned by the agencies endpoint.
```
curl -XGET "localhost:8888/api/agencies?event_date=2020-04-06&zip_code=43201"
```
returns
```
{
  "agencies": [
    {
      "id": 6,
      "address": "3960 BROOKHAM DR",
      "city": "GROVE CITY",
      "state": "OH",
      "zip": "43123",
      "phone": "614-317-9482",
      "name": "Mid-Ohio Foodbank - Kroger Community Pantry",
      "nickname": "MOF Kroger Pantry",
      "event_dates": [
        {
          "id": 1,
          "service": "Prepack Pantry",
          "start_time": "01:00 PM",
          "end_time": "03:00 PM",
          "date": "2020-04-06"
        },
        ......
        {
          "id": 12,
          "service": "Prepack Pantry",
          "start_time": "01:00 PM",
          "end_time": "03:00 PM",
          "date": "2020-04-25"
        }
      ]
    }
  ]
}
```

### CODE REVIEW

**Comment by davidpickering** [comment]
I'm liking this. I had been struggling to think through how we would use the end point to correctly feed back data without massive post processing. I think the API call as listed makes sense, but it needs an additional argument, or a clear way to "hack the date"
- event_date=2020-04-06 (already covered - good) - Gives us a way to get agencies & event_dates by date.
`
	AND `events`.status_publish_event = 1 
 	AND `events`.status_publish_event_dates = 1
`
- zip_code=43123 (already covered - good) - Gives us a way to get agencies and event_dates by geography.
- ??? some way to specify that we want only agencies that do not keep a detail of their event dates

`
	AND `events`.status_publish_event = 1 
 	AND `events`.status_publish_event_dates = 0
`
- There also is a use case for returning all agencies, without event_dates and just their general schedule information.
`	
	AND `events`.status_publish_event = 1 
`

These might even be different enough of questions & queries to merit two separate endpoints, but that is not my speciality. 

Basic Query for agencies + event dates (Production should have more Joins, Data, and Filters)
`
SELECT
events.event_id,
events.event_name,
event_dates.event_date_key,
event_dates.start_time_key,
event_dates.end_time_key,
events.address1,
events.address2,
events.city,
events.state,
events.zip,
events.status_publish_event,
events.status_publish_event_dates 
FROM
events
INNER JOIN event_dates ON `events`.event_id = event_dates.event_id 
WHERE
events.zip = 43123
AND events.status_publish_event = 1
AND events.status_publish_event_dates = 1
`

Basic query for Agencies (General Info only, no event_dates)
`
SELECT
	`events`.event_id,
	`events`.event_name,
	`events`.address1,
	`events`.address2,
	`events`.city,
	`events`.state,
	`events`.zip,
	`events`.status_publish_event,
	`events`.status_publish_event_dates,
	`events`.schedule_desc 
FROM
	`events` 
WHERE
	`events`.zip = 43123 
	AND `events`.status_publish_event = 1 
 	AND `events`.status_publish_event_dates = 0
`


From what I've learned about ReactJS so far:
1. Component to load the Foodbank section - API call as described in issue #25 
2. Component to Load the Food Resources (Wireframe says Resource Events) with event_dates. Based on the idea of calling the API for a zipcode once per date (outlined in this pull request)
3. Component to load additional resources, without event_dates.

To help us keep the concepts matched up to the Wireframes:

image

Also, to help communicate the different API scenarios:

- Red Circle (All agencies, regardless of status_publish_event_dates )
- Red Circle - Orange Circle (Only agencies that do not publish event dates status_publish_event_dates = 0)
- Orange Circle (Only agencies that publish event dates status_publish_event_dates  = 1)

image

**Comment by karengreene** [comment]
I think we need a way to "hack" the date too in order to test the api. We do need a way to test the API such that we can use some date other than using the current date. Maybe its as simple as creating two different service methods, one that takes the zip code and a date, and another that calls that method using the zip code and sends the current date to that method. It would make it a lot easier to test the list of pantry results.

**Comment by PhilNorman2** [comment]
Good discussion!  I like thinking as a consumer of the API.  I cloned the
repo and looking at the results this API is not returning the results for a
single date.  I haven’t had a chance to look at the code yet but it appears
to be returning event_dates for events that include the event date, in this
case 2020-04-03.  It also including event_dates prior to the event date:

{
                    "id": 4,
                    "service": "Prepack Pantry",
                    "start_time": "01:00 PM",
                    "end_time": "03:00 PM",
                    "date": "2020-04-03"
                },

I will look at the code  this morning but wanted to be sure we are on the
same page here.

I will venture to say that you could specify an event_date range in this
API.  However it seems like that would make a job of unpacking the results
especially if there was more than one agency in the results.  I had thought
of a separate event_dates API that accepted a date range allowing the
consumer to iterate the agencies API with those speicifc dates make the
UI’s job easier.

localhost:8888/api/agencies?event_date=2020-04-06&zip_code=43201

"agencies": [
        {
            "id": 6,
            "address": "3960 BROOKHAM DR",
            "city": "GROVE CITY",
            "state": "OH",
            "zip": "43123",
            "phone": "614-317-9482",
            "name": "Mid-Ohio Foodbank - Kroger Community Pantry",
            "nickname": "MOF Kroger Pantry",
            "event_dates": [
                {
                    "id": 1,
                    "service": "Prepack Pantry",
                    "start_time": "01:00 PM",
                    "end_time": "03:00 PM",
                    "date": "2020-04-06"
                },
                {
                    "id": 2,
                    "service": "Prepack Pantry",
                    "start_time": "01:00 PM",
                    "end_time": "03:00 PM",
                    "date": "2020-04-08"
                },
                {
                    "id": 3,
                    "service": "Prepack Pantry",
                    "start_time": "01:00 PM",
                    "end_time": "03:00 PM",
                    "date": "2020-04-10"
                },
                {
                    "id": 4,
                    "service": "Prepack Pantry",
                    "start_time": "01:00 PM",
                    "end_time": "03:00 PM",
                    "date": "2020-04-03"
                },
                {
                    "id": 5,
                    "service": "Prepack Pantry",
                    "start_time": "01:00 PM",
                    "end_time": "03:00 PM",
                    "date": "2020-04-13"
                },
                {
                    "id": 6,
                    "service": "Prepack Pantry",
                    "start_time": "01:00 PM",
                    "end_time": "03:00 PM",
                    "date": "2020-04-15"
                },
                {
                    "id": 7,
                    "service": "Prepack Pantry",
                    "start_time": "01:00 PM",
                    "end_time": "03:00 PM",
                    "date": "2020-04-17"
                },
                {
                    "id": 8,
                    "service": "Prepack Pantry",
                    "start_time": "01:00 PM",
                    "end_time": "03:00 PM",
                    "date": "2020-04-18"
                },
                {
                    "id": 9,
                    "service": "Prepack Pantry",
                    "start_time": "01:00 PM",
                    "end_time": "03:00 PM",
                    "date": "2020-04-20"
                },
                {
                    "id": 10,
                    "service": "Prepack Pantry",
                    "start_time": "01:00 PM",
                    "end_time": "03:00 PM",
                    "date": "2020-04-22"
                },
                {
                    "id": 11,
                    "service": "Prepack Pantry",
                    "start_time": "01:00 PM",
                    "end_time": "03:00 PM",
                    "date": "2020-04-24"
                },
                {
                    "id": 12,
                    "service": "Prepack Pantry",
                    "start_time": "01:00 PM",
                    "end_time": "03:00 PM",
                    "date": "2020-04-25"
                }
            ]
        }
    ]
}

**Comment by nvengal** [comment]
>  it appears
to be returning event_dates for events that include the event date, in this
case 2020-04-03.  It also including event_dates prior to the event date
@PhilNorman2 yup, you're right. Good catch. I think that the api should return all the upcoming event dates for the venue and then the front end can decide how they should be displayed. There's no point returning dates in the past. I'll update the pr to filter those out.

**Comment by nvengal** [comment]
For now let's delay figuring out the best way to do an event range. We can talk about that and implement it in a separate pr based on what we decide, distinct endpoint or modification to the existing.

**Comment by nvengal** [comment]
re: @davidpickering 
> event_date=2020-04-06 (already covered - good) - Gives us a way to get agencies & event_dates by date.
AND events.status_publish_event = 1 AND events.status_publish_event_dates = 1

Thanks for spelling out what I need to add to the query here. I'll modify the pr to include these two fields as well.

> zip_code=43123 (already covered - good) - Gives us a way to get agencies and event_dates by geography.

:+1: 

> ??? some way to specify that we want only agencies that do not keep a detail of their event dates
ANDevents.status_publish_event = 1 AND events.status_publish_event_dates = 0

I agree that we need this, but I'm hoping to open a separate pr for this work. Keeping each PR smaller helps make them easier to review and understand.

> There also is a use case for returning all agencies, without event_dates and just their general schedule information.
AND events.status_publish_event = 1

Let me think about the best way to expose this. Maybe it should just be the default behavior when you don't search on a specific date. Would we ever want to expose agencies with `events.status_publish_event = 0`?

**Comment by PhilNorman2** [comment]
Absolutely, one PR at a time.

**Comment by PhilNorman2** [comment]
I suggest adding the following:

default_scope { active }
scope :active, -> { where(status_id: 1) }

to the event and event_date models

**Comment by davidpickering** [comment]
> Would we ever want to expose agencies with events.status_publish_event = 0?

@nvengal That is an easy one - No! We want any and all of the API calls to only expose events with the status_publish_event = 1. This is our simple binary flag for publish/do not publish. While not asked, we also want to 100% of the time follow the events.status_id = 1 flag as well. This separates out old events that no longer operate.

> Absolutely, one PR at a time.

Understood, only hang one thing on the Christmas tree at a time.

> yup, you're right. Good catch. I think that the api should return all the upcoming event dates for the venue and then the front end can decide how they should be displayed. There's no point returning dates in the past. I'll update the pr to filter those out.

Okay, I'm seeing this now from the front end's point of view. If you get the data back: agencies=>event_dates{} you can go through each agency, and then each event_date you could look for a date container, add data to an existing container, or make a new one for the event_date data. 

> "agencies": [
        {
            "id": 6,
            "address": "3960 BROOKHAM DR",
            "city": "GROVE CITY",
            "state": "OH",
            "zip": "43123",
            "phone": "614-317-9482",
            "name": "Mid-Ohio Foodbank - Kroger Community Pantry",
            "nickname": "MOF Kroger Pantry",
            "event_dates": [
                {
                    "id": 1,
                    "service": "Prepack Pantry",
                    "start_time": "01:00 PM",
                    "end_time": "03:00 PM",
                    "date": "2020-04-06"
                },
                {
                    "id": 2,
                    "service": "Prepack Pantry",
                    "start_time": "01:00 PM",
                    "end_time": "03:00 PM",
                    "date": "2020-04-08"
                },

^^^^^ It is awesome seeing that response come to shape. I'm sure we'll find additional refinements, but that is just what we're looking for:

Great work everyone!

**Comment by nvengal** [comment]
Alright, I think I've gotten most of the feedback implemented.
Here are the ways you can query the agencies api:

- `/api/agencies?zip_code=43201`
Returns all agencies that are associated to foodbanks that service the zip code's county.
I think that this query is actually temporary. In a future state there will be a join table between agencies and zips and I believe that we will be using that table to determine the set of agencies to return. Mark and David know more about this than I do.
```
"SELECT DISTINCT `locations`.* FROM `locations` INNER JOIN `foodbanks_mini` ON `foodbanks_mini`.`status_id` = 1 AND `foodbanks_mini`.`fb_id` = `locations`.`primary_fb_id` INNER JOIN `foodbank_counties` ON `foodbank_counties`.`fb_id` = `foodbanks_mini`.`fb_id` INNER JOIN `CNTY` ON `CNTY`.`FIPS` = `foodbank_counties`.`fips` INNER JOIN `zip_codes` ON `zip_codes`.`priority` = 1 AND `zip_codes`.`fips` = `CNTY`.`FIPS` WHERE `locations`.`status_id` = 1 AND `zip_codes`.`zip_code` = '43201'"
```

- `/api/agencies?event_date=2020-04-25`
Returns all agencies that have an event on 2020-04-25.
```
"SELECT DISTINCT `locations`.* FROM `locations` INNER JOIN `events` ON `events`.`status_id` = 1 AND `events`.`status_publish_event` = 1 AND `events`.`loc_id` = `locations`.`loc_id` INNER JOIN `events` `events_locations_join` ON `events_locations_join`.`status_id` = 1 AND `events_locations_join`.`status_publish_event` = 1 AND `events_locations_join`.`loc_id` = `locations`.`loc_id` INNER JOIN `event_dates` ON `event_dates`.`status_id` = 1 AND `event_dates`.`status_publish` = 1 AND `event_dates`.`event_id` = `events_locations_join`.`event_id` AND (event_date_key >= '20200406') WHERE `locations`.`status_id` = 1 AND `events`.`status_id` = 1 AND `events`.`status_publish_event` = 1 AND `events`.`status_publish_event_dates` = 1 AND `event_dates`.`event_date_key` = 20200425"
```
There's some duplication in this query around the various status checks = 1. I think it's because I tried to do something cute and merge two different queries programatically. I don't think it's an issue, but we can revisit it if we need to.

- `/api/agencies?event_date=2020-04-25&zip_code=43030`
Searches on both date and zip_code at once.
```
"SELECT DISTINCT `locations`.* FROM `locations` INNER JOIN `foodbanks_mini` ON `foodbanks_mini`.`status_id` = 1 AND `foodbanks_mini`.`fb_id` = `locations`.`primary_fb_id` INNER JOIN `foodbank_counties` ON `foodbank_counties`.`fb_id` = `foodbanks_mini`.`fb_id` INNER JOIN `CNTY` ON `CNTY`.`FIPS` = `foodbank_counties`.`fips` INNER JOIN `zip_codes` ON `zip_codes`.`priority` = 1 AND `zip_codes`.`fips` = `CNTY`.`FIPS` INNER JOIN `events` ON `events`.`status_id` = 1 AND `events`.`status_publish_event` = 1 AND `events`.`loc_id` = `locations`.`loc_id` INNER JOIN `events` `events_locations_join` ON `events_locations_join`.`status_id` = 1 AND `events_locations_join`.`status_publish_event` = 1 AND `events_locations_join`.`loc_id` = `locations`.`loc_id` INNER JOIN `event_dates` ON `event_dates`.`status_id` = 1 AND `event_dates`.`status_publish` = 1 AND `event_dates`.`event_id` = `events_locations_join`.`event_id` AND (event_date_key >= '20200406') WHERE `locations`.`status_id` = 1 AND `zip_codes`.`zip_code` = '43030' AND `events`.`status_id` = 1 AND `events`.`status_publish_event` = 1 AND `events`.`status_publish_event_dates` = 1 AND `event_dates`.`event_date_key` = 20200425"
```

This can definitely use some refinement, but I'm happy with it as a start.
The high points are the addition of all the various status checks and the ability to scope by date.
The following have been added as default scopes so they apply any time you query these objects:
- Events
  - status_id: 1
  - status_publish_event: 1
  - status_publish_event_date: 1 (optional)
- EventDate
  - status_id: 1
  - status_publish: 1
  - events.status_publish_event_dates: 1
  - event_date has not already occurred

**Comment by karengreene** [comment]
In order to show up in 'Resource Event' section, the following needs to be true:
status_id: 1
status_publish_event: 1
status_publish_event_date: 1 
Need to have entry in event_date table within a specified time frame

**Comment by karengreene** [comment]
David, Phil and I met and discussed the query and the following changes need to be made in the agency query:
(event_date_key >= submitted date thru API) 
AND event_dates.published_date_key <= todays date 

This makes the updated query updated as follows *changes in bold*:

SELECT DISTINCT `locations`.* FROM `locations` 
INNER JOIN `foodbanks_mini` ON `foodbanks_mini`.`status_id` = 1 AND `foodbanks_mini`.`fb_id` = `locations`.`primary_fb_id` 
INNER JOIN `foodbank_counties` ON `foodbank_counties`.`fb_id` = `foodbanks_mini`.`fb_id` 
INNER JOIN `CNTY` ON `CNTY`.`FIPS` = `foodbank_counties`.`fips` 
INNER JOIN `zip_codes` ON `zip_codes`.`priority` = 1 AND `zip_codes`.`fips` = `CNTY`.`FIPS` 
INNER JOIN `events` ON `events`.`status_id` = 1 AND `events`.`status_publish_event` = 1 AND `events`.`loc_id` = `locations`.`loc_id` INNER JOIN `events` `events_locations_join` ON `events_locations_join`.`status_id` = 1 AND `events_locations_join`.`status_publish_event` = 1 AND `events_locations_join`.`loc_id` = `locations`.`loc_id` 
INNER JOIN `event_dates` ON `event_dates`.`status_id` = 1 AND `event_dates`.`status_publish` = 1 AND `event_dates`.`event_id` = `events_locations_join`.`event_id` AND **(event_date_key >= submitted date thru API)**
WHERE `locations`.`status_id` = 1 AND `zip_codes`.`zip_code` = '43030' 
	AND `events`.`status_id` = 1 AND `events`.`status_publish_event` = 1 
    AND `events`.`status_publish_event_dates` = 1 
    **AND event_dates.published_date_key <= todays date**

**Comment by karengreene** [comment]
Update JSON will include address and distance for the events.  There is now an event_dates under events.  Service is under events.


"agencies": [
{
"id": 6,
"address": "3960 BROOKHAM DR",
"city": "GROVE CITY",
"state": "OH",
"zip": "43123",
"phone": "614-317-9482",
"name": "Mid-Ohio Foodbank - Kroger Community Pantry",
"nickname": "MOF Kroger Pantry"
"events":
[
	{
		"name": Mobile Pantry A
	    "address:" "123 first address"
		"distance:"  This is the distance to the 123 first address
		"service": "Prepack Pantry"
		
		"event_dates": 
		[
			{
			   "id": 1,
				"start_time": "01:00 PM",
				"end_time": "03:00 PM",
				"date": "2020-04-06"
			},	
			{
				"id": 2,
				"start_time": "01:00 PM",
				"end_time": "03:00 PM",
				"date": "2020-04-08"
			}
		]
	},
	{
		"name": "Mobile Pantry B"
	    "address: "456 different street"
		"distance:"  This is the distance to the 456 different address
		"service": "Prepack Pantry"
		
		"event_dates": 
		[
			{
			   "id": 1,
				"start_time": "01:00 PM",
				"end_time": "03:00 PM",
				"date": "2020-04-06"
			},	
			{
				"id": 2,
				"start_time": "01:00 PM",
				"end_time": "03:00 PM",
				"date": "2020-04-08"
			}
		]
	}
]

**Pull request merged**
